### ISSUE TITLE
Tensorflow 2 gives error

### ISSUE THREAD

**Issue by tanjafranziskapfaffel** [Akashtyagi08/Pretrained-im2txt-single_instance#1]
FYI: Running the code with Tensorflow 2 is not working, as there is no Module tensorflow.contrib (also see here: https://github.com/tensorflow/tensorflow/issues/31350). I downgraded to tensorflow==1.15 and it works now.

**Comment by Akashtyagi** [comment]
Thanks for reporting it. I will add this to the readme.
