### ISSUE TITLE
Image gets deleted from folder after running

### ISSUE THREAD

**Issue by tanjafranziskapfaffel** [Akashtyagi08/Pretrained-im2txt-single_instance#3]
The image used to get a caption is deleted in the folder "images" after running the code. I do not know why, is this intention?

**Comment by Akashtyagi** [comment]
Yes, this was done intentional as per my previous need. Just comment this line [line no.53](https://github.com/Akashtyagi08/Pretrained-im2txt-single_instance/blob/caa252d867dec4cecc8cb426a3a941713ec9753b/im2txt.py#L53)

**Comment by tanjafranziskapfaffel** [comment]
ok, thanks for the quick answer!
