### ISSUE TITLE
Checksum does not match: stored 270509511 vs. calculated on the restored bytes 2065416399

### ISSUE THREAD

**Issue by Mesilenceki** [Akashtyagi08/Pretrained-im2txt-single_instance#4]
Hey 
I am trying to restore the model while it shows that your checkpoint doesn't match with the original model.

**Comment by Akashtyagi** [comment]
Can you please share sceenshots of the error. Also please make sure your Tensorflow version match the required .

**Comment by Mesilenceki** [comment]
Thank you I have fixed that problem.

**Comment by Akashtyagi** [comment]
Great. Closing the issue.

**Comment by audepe** [comment]
I'm experiencing the same problem. Can you tell me how did you fix it? @Mesilenceki

**Comment by lalitkishorevyas** [comment]
@Mesilenceki how you solved the issue @Akashtyagi08
